---
# tasks file for postgres

- name: Update cache
  apt:
    update_cache: yes


- name: Install PostgreSQL
  apt:
    name:
      - "postgresql-{{ version }}"
      - postgresql-contrib
    state: present


- name: Create PostgreSQL data directory
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'


- name: Copy PostgreSQL data to new directory
  command: rsync -av /var/lib/postgresql {{ data_dir }}
  async: 600
  poll: 0
  ignore_errors: yes


- name: Enabled and running PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes


- name: Set PostgreSQL data directory
  lineinfile:
    path: /etc/postgresql/{{ version }}/main/postgresql.conf
    regexp: "^data_directory ="
    line: "data_directory = '{{ data_dir }}/postgresql/{{ version }}/main'"


- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted
