Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.box_download_options = {"ssl-no-revoke" => true}
  config.vm.provider "virtualbox" do |v|
    v.name = "ubuntu-18.04"
    v.memory = 1024
    v.cpus = 1
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update &&  sudo apt-get -y upgrade
    sudo apt-get install -y python3 python-pip python3-pip python3-venv python3-virtualenv virtualenv software-properties-common
	sudo apt-get install -y libpq-dev python-dev python3-psycopg2
	sudo pip3 install psycopg2
	sudo apt-get install -y python3-django
  SHELL
  config.vm.provision "file", source: "./file.txt", destination: "~/scripts/"
end