---
- name: Install Docker
  hosts: test
  become: yes
  tasks:
    - name: Updates packages
      apt:
        update_cache: yes
      become: yes

    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Create keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory

    - name: Check that the GPG key file
      stat:
        path: /etc/apt/keyrings/docker.gpg
      register: stat_result

    - name: Add Docker's official GPG key to keyring
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      when: not stat_result.stat.exists


    - name: Check docker repo
      stat:
        path: /etc/apt/sources.list.d/docker.list
      register: stat_result_repo

    - name: Set up Docker repository
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      when: not stat_result_repo.stat.exists


    - name: Updates packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
         - docker-ce
         - docker-ce-cli
         - containerd.io
         - docker-buildx-plugin
         - docker-compose-plugin
        state: present


    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started
